### ISSUE TITLE
Haematology card colors

### ISSUE THREAD

**Issue by rofe** [hlxsites/medicalcontent-astrazeneca#14]
pages under haematology should use cards with different colors than thoe under breast cancer.

**Comment by KnightJam1** [comment]
Do you mind if I work on this?

**Comment by rofe** [comment]
@KnightJam1 sure, feel free to send a pull request!

The colors are found [here](https://medicalcontent.astrazeneca.com/haematology/elevate-rr/introduction#related%20content) and need to be added [here](https://github.com/hlxsites/medicalcontent-astrazeneca/blob/main/blocks/cards/cards.css) with a `.haematology` prefix.

**Comment by KnightJam1** [comment]
Thank you! I'll get working on it!

**Comment by KnightJam1** [comment]
Sorry about the lack of input, I'll be more free tomorrow to really get some more work done on this.

**Comment by rofe** [comment]
Any update, @KnightJam1? It would be great to have something in the next 12h... no worries otherwise, I'll take care of it.

**Comment by KnightJam1** [comment]
Hi, so sorry about all of this, I've had real difficulty finding time to really work on this. I'll try my best to get you a working solution in the next 12 hours. I have no lectures (or cousin's weddings) to attend tomorrow, so I can get some work in now, and again in the morning.
Apologies again about the hassle, and I really appreciate your patience on this matter.

**Comment by KnightJam1** [comment]
Hi, great news, I can change the card colours!
There are only 2 Haematology cards, and the second one is grey. Would you like me to add colour codes for more cards that may get added in the future, and would you like the second card to remain grey?

**Comment by KnightJam1** [comment]
If you don't need either, then I'm ready to make a pull request to close this issue!
Thanks again for all your help and patience!

**Comment by rofe** [comment]
> Would you like me to add colour codes for more cards 

In fact yes, sorry for not being more specific. See the small cards under "related content" [here](https://medicalcontent.astrazeneca.com/haematology/elevate-rr/introduction#related%20content). I added them now.

Thanks a lot for your help!
